var listItems = document.getElementsByTagName('li');
listItems[0].addEventListener('click',function(){
  window.open("mod1.html","_blank")
});
listItems[1].addEventListener('click',function(){
  window.open("mod2.html","_blank")
});
listItems[2].addEventListener('click',function(){
  window.open("mod3.html","_blank")
})
listItems[3].addEventListener('click',function(){
  window.open("mod4.html","_blank")
})
listItems[4].addEventListener('click',function(){
  window.open("mod5.html","_blank")
});
listItems[5].addEventListener('click',function(){
  window.open("mod6.html","_blank")
});
listItems[6].addEventListener('click',function(){
  window.open("mod7.html","_blank")
})
listItems[7].addEventListener('click',function(){
  window.open("mod8.html","_blank")
})
listItems[8].addEventListener('click',function(){
  window.open("mod9.html","_blank")
})
listItems[9].addEventListener('click',function(){
  window.open("mod10.html","_blank")
})
listItems[10].addEventListener('click',function(){
  window.open("mod11.html","_blank")
})
listItems[11].addEventListener('click',function(){
  window.open("mod12.html","_blank")
})

